name: utua_test
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 3.2.1
  firebase_core: 1.19.1
  email_validator: 2.1.17


dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  